2019/07/24 07:49:59 [error] 7#7: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /getDrivers HTTP/2.0", upstream: "http://172.23.0.4:3002/getDrivers", host: "localhost:3002"
2019/07/24 07:51:39 [error] 7#7: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /getDrivers HTTP/2.0", upstream: "http://172.23.0.4:3002/getDrivers", host: "localhost:3002"
2019/07/24 07:51:40 [error] 7#7: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /getDrivers HTTP/2.0", upstream: "http://172.23.0.4:3002/getDrivers", host: "localhost:3002"
2019/07/24 07:51:40 [error] 7#7: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /getDrivers HTTP/2.0", upstream: "http://172.23.0.4:3002/getDrivers", host: "localhost:3002"
2019/07/24 07:51:40 [error] 7#7: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /getDrivers HTTP/2.0", upstream: "http://172.23.0.4:3002/getDrivers", host: "localhost:3002"
2019/07/24 07:51:40 [error] 7#7: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /getDrivers HTTP/2.0", upstream: "http://172.23.0.4:3002/getDrivers", host: "localhost:3002"
2019/07/24 08:08:18 [error] 8#8: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /getDrivers HTTP/2.0", upstream: "http://172.23.0.6:3002/getDrivers", host: "localhost:3002"
2019/07/24 08:10:32 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: , request: "GET /getDrivers HTTP/2.0", upstream: "http://172.23.0.2:3000/getDrivers", host: "localhost:3002"
2019/07/25 07:33:47 [error] 8#8: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /?encoding=text HTTP/1.1", upstream: "http://172.19.0.3:3000/?encoding=text", host: "localhost:3001"
2019/07/25 07:51:14 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET / HTTP/2.0", upstream: "http://172.19.0.6:3000/", host: "localhost:3001"
2019/07/25 07:51:14 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.19.0.6:3000/favicon.ico", host: "localhost:3001", referrer: "https://localhost:3001/"
2019/07/25 13:12:32 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:12:37 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:12:40 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:12:43 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:12:46 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:12:49 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:12:54 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:13:04 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:13:20 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:13:47 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:14:41 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:15:43 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:16:44 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:17:45 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:18:46 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:19:50 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:20:52 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:21:53 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:22:54 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:23:56 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:24:57 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:25:59 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:27:00 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:28:01 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:29:03 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:30:05 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:31:06 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:32:07 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:33:09 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:34:10 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:35:12 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:36:13 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:37:16 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:38:17 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:39:19 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:40:20 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:41:22 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:42:23 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:43:25 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:44:26 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:45:30 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:46:31 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:47:33 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:48:34 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:49:36 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:50:37 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:51:38 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 13:52:40 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/07/25 16:40:56 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2019/07/25 16:40:56 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2019/07/25 16:40:56 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2019/07/25 16:46:10 [error] 7#7: *2 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.19.0.1, server: , request: "GET /getNearestDriver?lat=48&lon=7.04 HTTP/2.0", upstream: "http://172.19.0.7:3000/getNearestDriver?lat=48&lon=7.04", host: "localhost:3002"
2019/07/25 16:46:13 [error] 7#7: *2 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.19.0.1, server: , request: "GET /setOnline/3?lat=48&lon=7.0444 HTTP/2.0", upstream: "http://172.19.0.7:3000/setOnline/3?lat=48&lon=7.0444", host: "localhost:3002"
2019/07/25 16:47:12 [error] 7#7: *2 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.19.0.1, server: , request: "GET /setOffline/3 HTTP/2.0", upstream: "http://172.19.0.7:3000/setOffline/3", host: "localhost:3002"
2019/07/29 14:59:50 [error] 7#7: *48 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /api/v1/admin/branches HTTP/2.0", upstream: "http://172.19.0.3:3000/api/v1/admin/branches", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/29 15:32:34 [error] 7#7: *55 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /api/v1/admin/branches HTTP/2.0", upstream: "http://172.19.0.3:3000/api/v1/admin/branches", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/29 15:32:36 [error] 7#7: *55 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /api/v1/admin/branches HTTP/2.0", upstream: "http://172.19.0.3:3000/api/v1/admin/branches", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/30 07:30:19 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /api/v1/admin/branches HTTP/2.0", upstream: "http://172.19.0.4:3000/api/v1/admin/branches", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/30 07:30:20 [error] 7#7: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /api/v1/admin/branches HTTP/2.0", upstream: "http://172.19.0.4:3000/api/v1/admin/branches", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/30 07:40:29 [error] 7#7: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /api/v1/admin/regions HTTP/2.0", upstream: "http://172.19.0.4:3000/api/v1/admin/regions", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/30 07:40:32 [error] 7#7: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /api/v1/admin/regions HTTP/2.0", upstream: "http://172.19.0.4:3000/api/v1/admin/regions", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/30 14:45:26 [error] 7#7: *138 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "POST /api/v1/mobile/requests HTTP/2.0", upstream: "http://172.19.0.4:3000/api/v1/mobile/requests", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/30 15:27:09 [error] 6#6: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: , request: "GET /getNearestDriver?lat=66&lon=77.04 HTTP/2.0", upstream: "http://172.19.0.3:3000/getNearestDriver?lat=66&lon=77.04", host: "localhost:3002"
2019/07/31 13:35:52 [error] 6#6: *5 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.18.0.1, server: , request: "POST /api/v1/mobile/requests HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/mobile/requests", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/31 13:36:25 [error] 6#6: *5 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.18.0.1, server: , request: "POST /api/v1/mobile/requests HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/mobile/requests", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/31 13:36:25 [error] 6#6: *5 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.18.0.1, server: , request: "POST /api/v1/mobile/requests HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/mobile/requests", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/31 13:36:25 [error] 6#6: *5 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.18.0.1, server: , request: "POST /api/v1/mobile/requests HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/mobile/requests", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/31 13:36:25 [error] 6#6: *5 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.18.0.1, server: , request: "POST /api/v1/mobile/requests HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/mobile/requests", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/07/31 13:39:38 [error] 7#7: *3 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 172.18.0.1, server: , request: "POST /api/v1/mobile/requests HTTP/2.0", upstream: "http://172.18.0.2:3000/api/v1/mobile/requests", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/08/02 15:10:21 [alert] 1#1: worker process 8 exited on signal 9
2019/08/02 15:10:21 [alert] 1#1: worker process 9 exited on signal 9
2019/08/03 13:06:23 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2019/08/03 13:06:23 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2019/08/05 16:59:56 [alert] 1#1: worker process 8 exited on signal 9
2019/08/07 07:44:36 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/ HTTP/2.0", upstream: "http://172.18.0.4:3000/docs/", host: "localhost:3000"
2019/08/07 07:44:36 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.4:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/08/07 07:44:41 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/ HTTP/2.0", upstream: "http://172.18.0.4:3000/docs/", host: "localhost:3000"
2019/08/07 07:44:41 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.4:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/08/07 07:44:44 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/ HTTP/2.0", upstream: "http://172.18.0.4:3000/docs/", host: "localhost:3000"
2019/08/07 07:44:44 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.4:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/08/07 07:44:44 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/ HTTP/2.0", upstream: "http://172.18.0.4:3000/docs/", host: "localhost:3000"
2019/08/07 07:44:44 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.4:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/08/07 07:44:44 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/ HTTP/2.0", upstream: "http://172.18.0.4:3000/docs/", host: "localhost:3000"
2019/08/07 07:44:44 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.4:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/08/07 07:44:44 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/ HTTP/2.0", upstream: "http://172.18.0.4:3000/docs/", host: "localhost:3000"
2019/08/07 07:44:44 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.4:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/"
2019/08/07 07:44:51 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/admin HTTP/2.0", upstream: "http://172.18.0.4:3000/docs/admin", host: "localhost:3000"
2019/08/07 07:44:51 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.4:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin"
2019/08/07 07:44:53 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/admin HTTP/2.0", upstream: "http://172.18.0.4:3000/docs/admin", host: "localhost:3000"
2019/08/07 07:44:53 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.4:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin"
2019/08/07 07:47:55 [error] 6#6: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/admin HTTP/2.0", upstream: "http://172.18.0.4:3000/docs/admin", host: "localhost:3000"
2019/08/07 07:47:55 [error] 6#6: *30 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.4:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin"
2019/08/08 16:32:42 [error] 7#7: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.7:3000/docs/mobile/", host: "localhost:3000"
2019/08/08 16:32:42 [error] 7#7: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.7:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/08 16:32:43 [error] 7#7: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.7:3000/docs/mobile/", host: "localhost:3000"
2019/08/08 16:32:43 [error] 7#7: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.7:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/08 16:32:44 [error] 7#7: *58 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.7:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:06:52 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:06:53 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/09 13:06:54 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:06:54 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/09 13:06:54 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:06:54 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/09 13:06:55 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:06:55 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/09 13:06:55 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:06:55 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/09 13:06:55 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:06:55 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/09 13:06:55 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:06:56 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/09 13:06:56 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:06:56 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/09 13:06:56 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:06:56 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/09 13:07:04 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:07:04 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/09 13:07:06 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:07:06 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/09 13:08:12 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/09 13:08:42 [error] 6#6: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:39 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:40 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:42 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:42 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:42 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:42 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:43 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:43 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:43 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:43 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:43 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:43 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:45 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:45 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:45 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:45 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:45 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:45 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:45 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:45 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:45 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:45 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:45 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:46 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:46 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:46 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:23:46 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:23:46 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:26:32 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:26:32 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:26:33 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:26:33 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:26:34 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:26:34 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 13:26:34 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 13:26:34 [error] 6#6: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 14:57:07 [error] 6#6: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 14:57:07 [error] 6#6: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 14:57:08 [error] 6#6: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 14:57:09 [error] 6#6: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 14:57:09 [error] 6#6: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 14:57:09 [error] 6#6: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 14:57:09 [error] 6#6: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 14:57:10 [error] 6#6: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 14:57:10 [error] 6#6: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 14:57:10 [error] 6#6: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 14:58:06 [error] 6#6: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/12 14:58:06 [error] 6#6: *80 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/12 19:04:07 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2019/08/13 06:31:20 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/mobile/ HTTP/2.0", upstream: "http://172.18.0.6:3000/docs/mobile/", host: "localhost:3000"
2019/08/13 06:31:20 [error] 6#6: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.6:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/mobile/"
2019/08/13 16:38:27 [alert] 1#1: worker process 7 exited on signal 9
2019/08/16 12:02:21 [alert] 1#1: worker process 9 exited on signal 9
2019/08/17 19:19:44 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2019/08/17 19:19:44 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2019/08/17 19:19:44 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2019/08/19 20:06:32 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2019/08/21 16:40:38 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:40:40 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:40:41 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:40:41 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:40:42 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:40:43 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:40:44 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:40:44 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:40:45 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:40:46 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:40:47 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:40:48 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:40:48 [error] 6#6: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:45:46 [error] 6#6: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:45:48 [error] 6#6: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /api/v1/admin/services HTTP/2.0", upstream: "http://172.18.0.7:3000/api/v1/admin/services", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:47:46 [error] 6#6: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/admin/ HTTP/2.0", upstream: "http://172.18.0.7:3000/docs/admin/", host: "localhost:3000"
2019/08/21 16:47:47 [error] 6#6: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.7:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/21 16:47:48 [error] 6#6: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /docs/admin/ HTTP/2.0", upstream: "http://172.18.0.7:3000/docs/admin/", host: "localhost:3000"
2019/08/21 16:47:48 [error] 6#6: *41 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /favicon.ico HTTP/2.0", upstream: "http://172.18.0.7:3000/favicon.ico", host: "localhost:3000", referrer: "https://localhost:3000/docs/admin/"
2019/08/22 17:05:54 [alert] 1#1: worker process 9 exited on signal 9
2019/08/22 17:05:54 [alert] 1#1: worker process 7 exited on signal 9
2019/08/22 17:05:54 [alert] 1#1: worker process 8 exited on signal 9
2019/08/24 15:43:15 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2019/08/24 15:43:15 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2019/12/20 14:04:22 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev-location-service" in /etc/nginx/conf.d/https.conf:84
2019/12/20 14:04:25 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev-location-service" in /etc/nginx/conf.d/https.conf:84
2019/12/20 14:04:29 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev-location-service" in /etc/nginx/conf.d/https.conf:84
2019/12/20 14:04:32 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev-location-service" in /etc/nginx/conf.d/https.conf:84
2019/12/20 14:04:35 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev-location-service" in /etc/nginx/conf.d/https.conf:84
2019/12/20 14:04:38 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:04:46 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:04:54 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:05:09 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:05:36 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:06:29 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev-location-service" in /etc/nginx/conf.d/https.conf:84
2019/12/20 14:07:30 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:08:31 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:09:03 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:09:04 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:09:06 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:09:08 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:09:10 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:09:12 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:09:17 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:09:24 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev-location-service" in /etc/nginx/conf.d/https.conf:84
2019/12/20 14:09:27 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev-location-service" in /etc/nginx/conf.d/https.conf:84
2019/12/20 14:09:30 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev-location-service" in /etc/nginx/conf.d/https.conf:84
2019/12/20 14:09:33 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev-location-service" in /etc/nginx/conf.d/https.conf:84
2019/12/20 14:09:36 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:09:39 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev-location-service" in /etc/nginx/conf.d/https.conf:84
2019/12/20 14:09:44 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:09:53 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/20 14:10:07 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev-location-service" in /etc/nginx/conf.d/https.conf:84
2019/12/20 14:10:34 [emerg] 1#1: host not found in upstream "node-unit-drivers-node-dev" in /etc/nginx/conf.d/https.conf:41
2019/12/27 08:22:51 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:22:52 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:22:53 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:22:57 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:22:58 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:22:58 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:22:58 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:22:58 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:22:58 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:22:59 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:22:59 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:00 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:00 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:00 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:01 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:01 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:01 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:03 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:04 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:04 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:04 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:05 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:05 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:05 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:23:07 [error] 7#7: *1 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:25:02 [error] 7#7: *4 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:25:02 [error] 7#7: *4 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:25:03 [error] 7#7: *4 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:25:03 [error] 7#7: *4 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:25:03 [error] 7#7: *4 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2019/12/27 08:25:03 [error] 7#7: *4 directory index of "/var/www/public/" is forbidden, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:3071"
2020/01/13 19:26:30 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2020/01/18 12:52:22 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2020/01/22 20:26:07 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2020/01/24 06:50:35 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2020/01/31 17:56:10 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2020/02/04 18:32:22 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2020/02/09 18:31:16 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2020/02/11 18:17:02 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
2020/02/16 10:48:23 [warn] 1#1: "ssl_stapling" ignored, host not found in OCSP responder "ocsp.sectigo.com" in the certificate "/etc/nginx/ssl/cert.pem"
